### ISSUE TITLE
Связь

### ISSUE THREAD

**Issue by markeloff333** [unshame/Cardgame2017#1]
Добрый вечер, у меня есть к вам некоторые вопросы поповоду вашего проекта Cardgame2017. Как с вами можно связаться и обсудить более подробно?

**Comment by iliakulikov** [comment]
> Добрый вечер, у меня есть к вам некоторые вопросы поповоду вашего проекта Cardgame2017. Как с вами можно связаться и обсудить более подробно?

я бы тоже хотел связаться, как это можно сделать?
